export const lessons = {
  "similar-triangles": {
    notesSlug: null, category: "几何", difficulty: "入门", prerequisites: "三角形内角、比与简单方程", estimatedMinutes: 12,
    title: "相似三角形（Similar Triangles）图解：路灯下，影长和距离怎样变化？",
    published: "2026-10-11", updated: "2026-10-11", ogImage: "/images/learn/similar-triangles.png",
    description: "从路灯、人和影尖组成的两个直角三角形出发，标出对应角与边，连续放大重合，推导影长公式；分清影长和影尖的位置。",
    shortAnswer: "两个三角形有两组对应角相等，就由 AA 判定相似，对应边成比例。在本页的平地点光源模型中，灯高 H、身高 h、离灯距离 x、影长 s 满足 H/(x+s)=h/s，因此 s=hx/(H−h)。固定 H、h 时，s 与 x 成正比。",
    conditions: "地面水平，灯和人竖直，灯是固定的理想点光源，身体简化为竖直线段；所有长度使用米。有限远端影尖要求 H>h>0 且 x>0。实验限制灯高 H 为4–10、身高 h 为1–3、离灯距离 x 为1–8，步长0.5；这保证两三角形非退化、数值有限。忽略物体宽度、光源大小、散射和半影。",
    steps: [
      "命名三个距离：x 从灯底量到脚，s 从脚量到影尖 T，q=x+s 从灯底量到影尖。大三角形的高为 H、底为 q；小三角形的高为 h、底为 s。",
      "竖直线与水平地面垂直，所以两三角形各有一个直角；它们还共享影尖 T 处的锐角。两组对应角相等，由 AA 判定相似。",
      "把对应边写成同一顺序：大高/小高=大底/小底，即 H/h=(x+s)/s；也可写 H/(x+s)=h/s。不能把大底边写成 x。",
      "交叉相乘得 Hs=h(x+s)，整理为 (H−h)s=hx。由于 H>h，所以 s=hx/(H−h)，影尖位置 q=Hx/(H−h)。",
      "例子：H=6、h=2、x=4，影长 s=2×4/(6−2)=2 m，影尖距灯底 q=4+2=6 m。把 x 改为8，s=4 m、q=12 m；H、h 不变时比例系数 s/x=1/2 不变。",
      "以影尖 T 为中心，把小三角形放大 H/h 倍。脚映到灯底，头映到灯顶，T 保持不动，恰好覆盖大三角形。动画只是展示对应关系；一般结论来自 AA 相似与上述代数推导。"
    ],
    complexityLabel: "模型边界与计算",
    complexity: "只在最后显示时取近似值，计算中保留精度。x=0 时 s=0 是这一模型从右侧趋近的极限，但三角形退化，不能在那里用 AA 图形作证。x>0 时，H=h 的头顶光线水平，H<h 时越过头顶的射线向上，都没有本模型所需的有限远端地面影尖；不能除以0或将负结果叫影长。太阳光通常近似平行光，属于另一个模型，不能套用离路灯距离的结论。",
    mistakes: [
      "混淆影长 s 与影尖位置 q=x+s。H=6、h=2、x=4 时它们分别是2 m和6 m，不是同一个数。",
      "只因两个三角形都有直角就判相似：还需要第二组对应角相等，本例来自共同的影尖角。",
      "两三角形分别满足勾股定理，但这里连接它们大小的关键是相似比例；不能只把 x、h、s 当作同一个直角三角形的三边。",
      "影长与离灯距离成正比的前提是 H、h 固定。调灯高或身高会改变系数 h/(H−h)，不再是同一个正比例关系。",
      "放大倍数是对应边长的比 H/h，面积比则是 (H/h)²；图中的半透明轮廓在变换，不是人真的变高。"
    ],
    references: [{label:"Euclid《几何原本》VI.4：对应角相等的三角形，其对应边成比例",url:"https://mathcs.clarku.edu/~djoyce/elements/bookVI/propVI4.html"},{label:"University of Waterloo CEMC：相似与全等、相似三角形课程",url:"https://courseware.cemc.uwaterloo.ca/46?gid=161"},{label:"Mr. Yang：Related Rates 课堂的影子比例提醒（本页只讲相似，不讲求导）",url:"https://mryangteacher.weebly.com/unit-4-related-rates--applications-part-1.html"}],
    goals: ["由直角和共同角识别 AA 相似", "区分 x、s 和 x+s，并正确配对两组边", "观察缩放重合，解释固定条件下的正比例与模型边界"],
    summary: "灯高6 m、身高2 m，人离灯4 m时影长2 m、影尖距灯6 m。固定两种高度，离灯距离翻倍为8 m，影长变4 m、影尖距灯12 m。",
    invariant: "在平地、竖直、固定点光源且 H>h>0、x>0 的模型中，两三角形始终 AA 相似，H/h=(x+s)/s。以影尖为中心放大 H/h 倍，小三角形恰好覆盖大三角形。",
    question: "灯高6 m、身高2 m，人离灯4 m。若只把离灯距离改为8 m，影长和影尖距灯底分别是多少？若只改变身高，原来的 s/x=1/2 还保持吗？",
    answer: "影长4 m，影尖距灯底12 m。改变身高会改变 h/(H−h)，所以一般不再保持1/2；不能把三个距离混为一谈，也不能漏掉固定高度的条件。",
  },

  "binary-search": {
    notesSlug: "binary-search",
    category: "算法",
    difficulty: "入门",
    prerequisites: "数组下标、大小比较",
    estimatedMinutes: 10,
    title: "二分查找（Binary Search）图解：窗口怎样缩小",
    published: "2026-10-07",
    updated: "2026-10-07",
    ogImage: "/images/learn/binary-search.png",
    shortAnswer: "二分查找在有序数组中比较中点，每轮排除不可能的一半。本页闭区间版本命中时返回一个匹配下标，否则返回 -1。",
    conditions: "输入按非下降顺序排列，允许重复；数组可随机访问。重复目标只保证找到一个，不保证最左或最右。空数组直接返回 -1。图形输入限制为 1–8 个 ±999 整数，这不是算法本身的限制。",
    steps: ["在 [1, 3, 5, 7, 9] 中找 9：lo = 0，hi = 4，mid = 2，a[mid] = 5 < 9。", "排除中点及左侧：lo = 3，hi = 4，mid = 3，a[mid] = 7 < 9。", "再令 lo = 4，hi = 4，mid = 4，命中 9，返回下标 4。"],
    complexityLabel: "复杂度",
    complexity: "迭代查找最坏时间 O(log n)，额外空间 O(1)；空数组 O(1)。不包含预先排序的成本，也不包含页面为动画保存轨迹的开销。",
    mistakes: ["闭区间未命中后写 lo = mid 或 hi = mid，可能保留同一窗口而停滞。不要混用闭区间和半开区间模板。", "未排序就二分，排除一半的依据不成立；排序还会改变原始下标。", "C++ 使用 lo + (hi - lo) / 2 时，仍须保证下标和差值可表示；有符号整数溢出是未定义行为，本页小整数不模拟它。"],
    references: [{ label: "CP-Algorithms：Binary Search（不变量与复杂度）", url: "https://cp-algorithms.com/num_methods/binary_search.html" }],
    description: "逐步观察 lo、hi、mid，比较正确更新与窗口停滞，区分未命中和死循环。",
    goals: ["认出闭区间 [lo, hi] 与本轮中点", "解释为什么比较后必须跳过 mid", "区分窗口停滞与整数溢出"],
    summary: "有序数组 [1, 3, 5, 7, 9] 查找 9：窗口依次为 [0, 4]、[3, 4]、[4, 4]，最后返回下标 4。每次未命中都排除已经比较过的 mid。",
    invariant: "目标若存在，就仍在闭区间 [lo, hi] 中。正确更新为 lo = mid + 1 或 hi = mid - 1；lo > hi 时返回 -1。",
    question: "[1, 3] 查找 3，第一次 mid = 0。若写 lo = mid，下一轮窗口是什么？",
    answer: "仍是 [0, 1]，中点也仍是 0。窗口没有缩小。改成 lo = mid + 1 后窗口变为 [1, 1]，下一轮命中。",
  },
  "longest-increasing-subsequence": {
    notesSlug: "longest-increasing-subsequence",
    category: "算法",
    difficulty: "进阶",
    prerequisites: "数组、二分查找",
    estimatedMinutes: 15,
    title: "最长递增子序列（LIS）图解：替换结尾，还是延长",
    published: "2026-10-07",
    updated: "2026-10-10",
    ogImage: "/images/learn/longest-increasing-subsequence.png",
    shortAnswer: "最长递增子序列（LIS）是在保持原顺序、允许跳过元素的前提下，能取出的最长严格递增序列。维护每种长度的最小结尾 tails，其长度就是 LIS 长度。",
    conditions: "原数组无需排序，也不能先排序再求原问题。严格递增不允许相等；非下降允许相等。空数组长度为 0，单元素长度为 1。图形输入限制为 1–12 个 ±999 整数。",
    steps: ["输入 [3, 5, 7, 1, 2, 8]：依次读 3、5、7，tails 从 [] 延长为 [3, 5, 7]。", "读 1：替换第一个 ≥ 1 的结尾，得到 [1, 5, 7]；读 2 后得到 [1, 2, 7]。长度仍是 3。", "把 tails 的位置看作候选：严格递增判断 tails[i] ≥ x，非下降判断 tails[i] > x。tails 有序，所以两种判定都从 false 变为 true；二分寻找第一个 true。若所有位置都是 false（也包括空 tails），lower_bound / upper_bound 返回尾后位置 end，此时追加 x，不能解引用 end。", "读 8：没有 ≥ 8 的结尾，追加为 [1, 2, 7, 8]。答案长度 4；一条真实子序列是 [3, 5, 7, 8]。"],
    complexityLabel: "复杂度",
    complexity: "用随机访问数组保存 tails，并用二分定位时，最坏时间 O(n log n)，额外空间 O(n)；空数组 O(1)。页面复制逐帧快照的开销不代表算法本身的空间复杂度。",
    mistakes: ["把 tails 当作答案序列：各格可能来自不同子序列，恢复具体答案需要额外记录前驱。", "严格递增找第一个 ≥ x 的位置（lower_bound）；非下降找第一个 > x 的位置（upper_bound）。[2, 2, 2] 的两种答案分别是 1 和 3。", "子序列不要求连续。替换一个结尾不表示改动原数组，也不增加当前答案长度。"],
    references: [{ label: "CP-Algorithms：Longest increasing subsequence", url: "https://cp-algorithms.com/sequences/longest_increasing_subsequence.html" }, { label: "C++ 工作草案：lower_bound / upper_bound", url: "https://eel.is/c++draft/alg.binary.search" }],
    description: "一步一格观察 tails，切换严格递增与非下降，理解相等元素为何不能延长严格 LIS。",
    goals: ["理解 tails 每格对应的最小结尾", "对比 lower_bound 与 upper_bound", "解释 tails 不一定是一条真实子序列"],
    summary: "输入 [2, 2, 2]：严格递增时，每个 2 都落到第一个大于等于它的位置，tails 始终为 [2]，长度为 1；允许相等时，每个 2 都追加，非下降长度为 3。",
    invariant: "tails[i] 是已读前缀中，长度 i + 1 的递增子序列的最小结尾。它的长度是答案，但这些结尾未必来自同一条子序列。",
    question: "输入 [3, 5, 7, 1, 2, 8]，最终 tails = [1, 2, 7, 8]。它是一条原数组子序列吗？",
    answer: "不是。7 在 1、2 之前，不能按这个顺序取出。长度 4 仍然正确，例如原数组里的 [3, 5, 7, 8]。tails 保存的是各个长度的最小结尾。",
  },
  "binary-search-on-answer": {
    notesSlug: null,
    category: "算法", difficulty: "进阶", prerequisites: "二分查找、整数除法、单调性", estimatedMinutes: 15,
    title: "二分答案（Binary Search on Answer）图解：最早什么时候够用？",
    published: "2026-10-10", updated: "2026-10-10", ogImage: "/images/learn/binary-search-on-answer.png",
    shortAnswer: "二分答案把优化问题改成判定问题：不直接猜最优答案，而是问某个候选值是否可行。如果真假结果只有一次分界，就能每次排除一半候选范围，找到第一个可行值。这里搜索的是完成需求的最早整数秒数，不是数组里某个值的下标。",
    conditions: "机器从 0 秒同时开始、互不干扰，每台生产一件需要固定的正整数秒；只计算完整产品。需求是非负整数，机器至少一台。实验限制 1–4 台、每台 1–12 秒、需求 0–24 件，确保 JavaScript 整数精确且图形可读。一般算法不受此图形范围限制，但必须重新验证整数上界与溢出。",
    steps: [
      "先确定搜索空间：候选值 t 是经过的整数秒。每台耗时 kᵢ，t 秒内完成 floor(t / kᵢ) 件；总量 C(t) 是各台之和。enough(t) 判断 C(t) ≥ target。",
      "说明单调性：时间增加时，每台已完成的件数都不会减少，所以 C(t) 非下降。某时刻已经够用，所有更晚时刻都够用；某时刻不够，所有更早时刻都不够。",
      "用最快机器独自完成全部需求给出上界 U = min(kᵢ) × target。设 lo=0、hi=U，保持最早可行答案位于闭区间 [lo, hi]；这里不要求 lo 不可行。",
      "取 mid=lo+floor((hi-lo)/2)。若够用，hi=mid，保留这个可能最早的答案；否则 lo=mid+1，因为 mid 及更早都不行。lo<hi 时窗口严格缩小；相等时返回 lo。",
      "示例机器耗时 [2,3,7]，需求 8 件，上界 16。检查 8 秒：4+2+1=7，不够，区间变 [9,16]；检查 12 秒：6+4+1=11，够，变 [9,12]；检查 10 秒：5+3+1=9，够，变 [9,10]；检查 9 秒：4+3+1=8，够，合拢到 9。",
      "确认最优性：9 秒完成 8 件，8 秒只有 7 件，因此最早是 9 秒。若需求为 0，答案直接是 0；两台同为 4 秒、需求 7 件时，12 秒只有 6 件，16 秒有 8 件，答案为 16。"
    ],
    complexityLabel: "复杂度与整数边界",
    complexity: "n 台机器，上界 U=min(kᵢ)×target。每次判定 O(n)，二分 O(log(U+1)) 次，总时间 O(n log(U+1))，算法额外空间 O(1)（不含输入）。需求为 0 可直接返回 0。图形为探索时间预计算参考边界、保存步骤和画产量阶梯，有独立展示开销，不能当作二分运行时间。C++ 示例的 kᵢ、target 至多 10⁹，上界至多 10¹⁸，用 long long；累计产量提前截断，防止溢出。",
    mistakes: [
      "把要搜的时间误当成机器数组下标。机器耗时不需要排序；这里依赖的是 enough(t) 的单调性。",
      "看见 true 就立即返回。它只说明这个时间够用，不代表最早；要令 hi=mid 继续向左找。",
      "把这里的 hi=mid 与原二分查找的 hi=mid-1 混用。查第一个 true 与查相等元素维护的目标不同；循环条件、区间含义和更新必须成套。",
      "没有证明单调性就套模板。[F,T,F,F,T,T,T,T] 在中点看到 F 并不能排除左边的 T。",
      "把尚未做完的产品算成件数，或让动画插值改变算法状态。产量用向下取整；画面可连续变化，但二分只检查整数秒。",
      "直接累加所有机器在大上界下的产量可能溢出。判定只需要知道是否够用，可在达到目标前提前返回；零耗时会除零，必须拒绝。"
    ],
    references: [
      { label: "CP-Algorithms：单调谓词与二分答案", url: "https://cp-algorithms.com/num_methods/binary_search.html#search-on-arbitrary-predicate" },
      { label: "USACO Guide：Binary Search on Monotonic Functions", url: "https://usaco.guide/silver/binary-search" },
      { label: "CSES：Factory Machines（并行生产问题；本站另设教学示例）", url: "https://cses.fi/problemset/task/1620/" }
    ],
    description: "拖动时间，看并行机器完成产品、产量阶梯跨过需求线；再让二分窗口逼近第一个可行时刻，理解为什么先证明单调性。",
    goals: ["区分搜索空间、判定函数与最优答案", "从生产过程证明真假分界的单调性", "解释为什么可行时保留 mid，不可行时跳过 mid"],
    summary: "机器 [2,3,7] 秒/件，目标 8 件；二分检查 8、12、10、9 秒，最终得到 9 秒。8 秒总量 7，9 秒总量 8。",
    invariant: "最早可行时间始终在 [lo,hi] 内。hi 本身可行；lo 可以可行，也可以不可行。每次比较后缩小区间，直到 lo=hi。",
    question: "两台机器都需要 4 秒一件，需求 7 件。12 秒够吗？最早多少秒？如果需求为 0 呢？",
    answer: "12 秒每台 3 件，总共 6 件，不够。16 秒每台 4 件，总共 8 件，最早 16 秒。需求为 0 时，最早 0 秒；无需启动生产。"
  },
  "pythagorean-theorem": {
    notesSlug: null,
    category: "几何",
    difficulty: "入门",
    prerequisites: "直角、正方形与三角形面积、平方和平方根",
    estimatedMinutes: 12,
    title: "勾股定理（Pythagorean Theorem）图解：四块三角形，拼出平方和",
    published: "2026-10-09",
    updated: "2026-10-11",
    ogImage: "/images/learn/pythagorean-theorem.png",
    shortAnswer: "在平面直角三角形中，两条直角边长为 a、b，直角对面的斜边长为 c，则 a² + b² = c²。它说的是三个正方形的面积关系，不是两条边长相加等于第三条边长。",
    conditions: "a、b、c 都是正的长度，并使用同一单位。a、b 的夹角必须是 90°，c 才是斜边；不能仅凭图形看起来像直角就套公式。本页讨论平面欧氏几何中的非退化三角形。反过来，在一个三角形中，若最长边 c 满足 a² + b² = c²，则 c 对面的角是直角，这就是勾股定理的逆定理。",
    steps: [
      "先准备四个全等的直角三角形，每块的直角边为 a、b，斜边为 c，面积都是 ab / 2；外框固定为边长 a + b 的正方形。",
      "摆法一：把四块三角形放在外框四角，直角朝外，四条斜边围出中间的四边形。它的边长都是 c；直角三角形的两个锐角之和为 90°，所以中间每个角也是 90°，余下的是面积 c² 的正方形。",
      "摆法二：在同一个外框中，只平移这四块三角形，让它们两两拼成两个 a × b 的长方形。两个长方形放在对角的区域，余下两个正方形，边长分别为 a、b，面积之和为 a² + b²。",
      "两种摆法都没有重叠或遗漏：同一个面积 (a + b)² 的外框，减去同四块三角形的总面积 4 × ab / 2，余下面积必然相等。因此 c² = (a + b)² − 4 × ab / 2 = a² + b²。这个论证适用于任意正的 a、b，并不只验证某一个数值例子。",
      "代入 a = 3、b = 4：外框面积为 7² = 49，四块三角形总面积为 4 × 6 = 24，余下 25。另一种摆法余下 3² + 4² = 9 + 16 = 25，所以 c² = 25，长度 c = 5。",
      "逆定理用来判定直角：已知一个三角形三边为 3、4、5，先选最长边 5，再验算 3² + 4² = 5²，可知 5 对面的角为 90°。这是从边长判断角度，方向与已知直角后求斜边不同。",
      "日期联想：2026 年 10 月 24 日按“月 / 日 / 两位年份”写作 10/24/26，恰好有 10² + 24² = 100 + 576 = 676 = 26²。WonderLab 与 Seattle Universal Math Museum 已公布当天的勾股主题活动；勾股数指满足 a² + b² = c² 的三个正整数；例如 1、1、√2 满足勾股定理，却不是勾股数。这里借日期说明一组勾股数，不把它当作通用日期格式或全球统一节日。此例是静态算式；上方实验的直角边滑块仍限 1–8，不能直接输入 10 和 24。",
    ],
    complexityLabel: "计算与适用范围",
    complexity: "已知两条直角边时，c = √(a² + b²)，长度取正平方根；已知斜边 c 和直角边 a 时，b = √(c² − a²)，且 c > a > 0。边长可为正实数，不要求整数，也不要求 a < b。图中的数值显示可能经过四舍五入，几何恒等式本身是精确的；改变图形的显示大小或只试几个数值，都不能代替一般证明。",
    mistakes: [
      "过早取近似值：计算过程中先保留根式，或使用计算器中的完整数值，最后再按题目要求取近似值；要求精确值时就保留根式。例如，边长为 1 的正方形，两条对角线总长为 2√2，保留两位小数是 2.83；若先把每条对角线取成 1.41，再相加就会得到 2.82。",
      "把任意最长边都叫斜边：只有直角三角形才有斜边，它总在直角对面。图形旋转以后，斜边的身份不变。",
      "把 a² + b² = c² 写成 a + b = c，或把 √(a² + b²) 拆成 a + b：3 和 4 的平方和是 25，开方得到 5，不是 7；c² 表示面积，c 才表示长度。",
      "忘记直角条件：两边长为 3、4，夹角为 60° 时，由余弦定理，第三边的平方 c² = 3² + 4² − 2 × 3 × 4 × cos 60° = 13，不等于 25。这里 c = √13，且不能把 c 称为斜边。非直角三角形不能直接对三边套用勾股定理，但可以向对边所在直线作高，在形成的两个直角三角形中分别使用；垂足也可能落在边的延长线上。能否求出未知量，还要看已知条件是否足够。",
      "以为拼图只要看起来能摆进去就算证明：必须说明两次使用同样大的外框、同四块三角形，并且各自无重叠、无遗漏；摆法一的中间图形还必须证明是正方形。",
      "把定理和逆定理混用：求边长要先有直角条件；判定直角则要先确认三边组成三角形，并比较最长边的平方与另外两边的平方和。测量值近似相等，只能说明在测量精度内接近直角。",
    ],
    references: [
      { label: "Euclid《几何原本》I.47：勾股定理（David E. Joyce 在线版；原证明与本页拼补法不同）", url: "https://mathcs.clarku.edu/~djoyce/elements/bookI/propI47.html" },
      { label: "Euclid《几何原本》I.48：勾股定理的逆定理", url: "https://mathcs.clarku.edu/~djoyce/elements/bookI/propI48.html" },
      { label: "OpenStax《Algebra and Trigonometry 2e》10.2：余弦定理与非直角三角形", url: "https://openstax.org/books/algebra-and-trigonometry-2e/pages/10-2-non-right-triangles-law-of-cosines" },
      { label: "WonderLab：2026 年 10 月 24 日勾股主题活动", url: "https://wonderlab.org/pythagorean-theorem-day/" },
      { label: "Seattle Universal Math Museum：Pythagorean Palooza（10/24/26）", url: "https://seattlemathmuseum.org/events/pythagorean-palooza" },
    ],
    description: "移动同样的四块直角三角形，比较 c² 与 a² + b² 两种剩余面积；从 3、4、5 的例子理解勾股定理，并用 60° 反例认清适用条件。",
    goals: ["找到直角对面的斜边，并区分边长与平方表示的面积", "解释同一外框减同四块三角形，为什么能证明 a² + b² = c²", "用逆定理判断直角，并识别非直角时不能套用的反例"],
    summary: "在 3、4、5 直角三角形的两种拼法中，外框面积都为 49，四块三角形面积都为 24，余下的 25 分别是 5² 与 3² + 4²。把 3、4 换成任意正的 a、b，面积守恒仍成立。若两边夹角改成 60°，第三边平方变成 13，不能继续套用勾股等式。",
    invariant: "两种摆法保持同一边长 a + b 的正方形外框，以及同四个面积 ab / 2 的全等直角三角形。它们在起点与终点的完整摆法中无重叠、无遗漏，因此余下的 c² 与 a² + b² 必然相等。",
    question: "一个三角形的两边是 3 和 4，就能断定第三边是 5 吗？若已知三边为 5、12、13，又该怎样判断它是否为直角三角形？",
    answer: "不能。还需要知道 3、4 两边的夹角是 90°；若夹角是 60°，第三边为 √13。对于 5、12、13，最长边是 13，且 5² + 12² = 25 + 144 = 169 = 13²，由逆定理可知 13 对面的角是直角。",
  },
} as const;
export type LessonSlug = keyof typeof lessons;
export function getLesson(slug: string) {
  return Object.prototype.hasOwnProperty.call(lessons, slug) ? lessons[slug as LessonSlug] : undefined;
}

/** Optional learning extensions; not prerequisites or a new lesson. */
export const lessonExtensions: Partial<Record<LessonSlug, { slug: LessonSlug; label: string; explanation: string }>> = {
  "similar-triangles": { slug: "pythagorean-theorem", label: "相关实验：勾股定理与直角条件", explanation: "勾股定理联系一个直角三角形的三边；相似比例联系两个三角形的对应边。先辨认图形和已知条件，再选择关系。" },
  "pythagorean-theorem": { slug: "similar-triangles", label: "继续探索：路灯下的相似三角形", explanation: "同样出现直角，求影长时还要连接两个三角形。通过对应角与对应边，理解为什么应先写相似比例。" },
  "longest-increasing-subsequence": {
    slug: "binary-search-on-answer", label: "继续探索：二分答案，寻找第一个可行时刻",
    explanation: "同样是找第一个 true，候选可以从 tails 的位置换成时间。注意：本课可能返回 end，表示没有满足条件的元素；二分答案课先证明 hi 可行，才在闭区间里收缩。不能把两者的区间边界与无解处理直接混用。",
  },
  "binary-search-on-answer": {
    slug: "longest-increasing-subsequence", label: "相关应用：LIS 中的 lower_bound 与 upper_bound",
    explanation: "换一个搜索空间：在有序 tails 中找第一个 ≥ x 或 > x 的位置。若不存在就返回 end 并追加，而不是返回一个可解引用的元素；这与本课已有可行 hi 的前提不同。",
  },
};
