export const lessons = {
  "binary-search": {
    category: "算法",
    difficulty: "入门",
    prerequisites: "数组下标、大小比较",
    estimatedMinutes: 10,
    title: "二分查找（Binary Search）图解：窗口怎样缩小",
    published: "2026-10-07",
    updated: "2026-10-07",
    ogImage: "/images/learn/binary-search.png",
    shortAnswer: "二分查找在有序数组中比较中点，每轮排除不可能的一半。本页闭区间版本命中时返回一个匹配下标，否则返回 -1。",
    conditions: "输入按非下降顺序排列，允许重复；数组可随机访问。重复目标只保证找到一个，不保证最左或最右。空数组直接返回 -1。图形输入限制为 1–8 个 ±999 整数，这不是算法本身的限制。",
    steps: ["在 [1, 3, 5, 7, 9] 中找 9：lo = 0，hi = 4，mid = 2，a[mid] = 5 < 9。", "排除中点及左侧：lo = 3，hi = 4，mid = 3，a[mid] = 7 < 9。", "再令 lo = 4，hi = 4，mid = 4，命中 9，返回下标 4。"],
    complexity: "迭代查找最坏时间 O(log n)，额外空间 O(1)；空数组 O(1)。不包含预先排序的成本，也不包含页面为动画保存轨迹的开销。",
    mistakes: ["闭区间未命中后写 lo = mid 或 hi = mid，可能保留同一窗口而停滞。不要混用闭区间和半开区间模板。", "未排序就二分，排除一半的依据不成立；排序还会改变原始下标。", "C++ 使用 lo + (hi - lo) / 2 时，仍须保证下标和差值可表示；有符号整数溢出是未定义行为，本页小整数不模拟它。"],
    references: [{ label: "CP-Algorithms：Binary Search（不变量与复杂度）", url: "https://cp-algorithms.com/num_methods/binary_search.html" }],
    description: "逐步观察 lo、hi、mid，比较正确更新与窗口停滞，区分未命中和死循环。",
    goals: ["认出闭区间 [lo, hi] 与本轮中点", "解释为什么比较后必须跳过 mid", "区分窗口停滞与整数溢出"],
    summary: "有序数组 [1, 3, 5, 7, 9] 查找 9：窗口依次为 [0, 4]、[3, 4]、[4, 4]，最后返回下标 4。每次未命中都排除已经比较过的 mid。",
    invariant: "目标若存在，就仍在闭区间 [lo, hi] 中。正确更新为 lo = mid + 1 或 hi = mid - 1；lo > hi 时返回 -1。",
    question: "[1, 3] 查找 3，第一次 mid = 0。若写 lo = mid，下一轮窗口是什么？",
    answer: "仍是 [0, 1]，中点也仍是 0。窗口没有缩小。改成 lo = mid + 1 后窗口变为 [1, 1]，下一轮命中。",
  },
  "longest-increasing-subsequence": {
    category: "算法",
    difficulty: "进阶",
    prerequisites: "数组、二分查找",
    estimatedMinutes: 15,
    title: "最长递增子序列（LIS）图解：替换结尾，还是延长",
    published: "2026-10-07",
    updated: "2026-10-07",
    ogImage: "/images/learn/longest-increasing-subsequence.png",
    shortAnswer: "最长递增子序列（LIS）是在保持原顺序、允许跳过元素的前提下，能取出的最长严格递增序列。维护每种长度的最小结尾 tails，其长度就是 LIS 长度。",
    conditions: "原数组无需排序，也不能先排序再求原问题。严格递增不允许相等；非下降允许相等。空数组长度为 0，单元素长度为 1。图形输入限制为 1–12 个 ±999 整数。",
    steps: ["输入 [3, 5, 7, 1, 2, 8]：依次读 3、5、7，tails 从 [] 延长为 [3, 5, 7]。", "读 1：替换第一个 ≥ 1 的结尾，得到 [1, 5, 7]；读 2 后得到 [1, 2, 7]。长度仍是 3。", "读 8：没有 ≥ 8 的结尾，追加为 [1, 2, 7, 8]。答案长度 4；一条真实子序列是 [3, 5, 7, 8]。"],
    complexity: "用随机访问数组保存 tails，并用二分定位时，最坏时间 O(n log n)，额外空间 O(n)；空数组 O(1)。页面复制逐帧快照的开销不代表算法本身的空间复杂度。",
    mistakes: ["把 tails 当作答案序列：各格可能来自不同子序列，恢复具体答案需要额外记录前驱。", "严格递增找第一个 ≥ x 的位置（lower_bound）；非下降找第一个 > x 的位置（upper_bound）。[2, 2, 2] 的两种答案分别是 1 和 3。", "子序列不要求连续。替换一个结尾不表示改动原数组，也不增加当前答案长度。"],
    references: [{ label: "CP-Algorithms：Longest increasing subsequence", url: "https://cp-algorithms.com/sequences/longest_increasing_subsequence.html" }, { label: "C++ 工作草案：lower_bound / upper_bound", url: "https://eel.is/c++draft/alg.binary.search" }],
    description: "一步一格观察 tails，切换严格递增与非下降，理解相等元素为何不能延长严格 LIS。",
    goals: ["理解 tails 每格对应的最小结尾", "对比 lower_bound 与 upper_bound", "解释 tails 不一定是一条真实子序列"],
    summary: "输入 [2, 2, 2]：严格递增时，每个 2 都落到第一个大于等于它的位置，tails 始终为 [2]，长度为 1；允许相等时，每个 2 都追加，非下降长度为 3。",
    invariant: "tails[i] 是已读前缀中，长度 i + 1 的递增子序列的最小结尾。它的长度是答案，但这些结尾未必来自同一条子序列。",
    question: "输入 [3, 5, 7, 1, 2, 8]，最终 tails = [1, 2, 7, 8]。它是一条原数组子序列吗？",
    answer: "不是。7 在 1、2 之前，不能按这个顺序取出。长度 4 仍然正确，例如原数组里的 [3, 5, 7, 8]。tails 保存的是各个长度的最小结尾。",
  },
} as const;
export type LessonSlug = keyof typeof lessons;
export function getLesson(slug: string) {
  return Object.prototype.hasOwnProperty.call(lessons, slug) ? lessons[slug as LessonSlug] : undefined;
}
